name: Bump Version
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version to release (e.g., 1.0.0)'
        required: true

jobs:
  bump-version:
    name: Bump Version and Create PR
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump project version
        run: |
          script=$(mktemp)
          printf "@tool extends MainLoop
          func _initialize():
          \tProjectSettings.set_setting('application/config/version', '${{ github.event.inputs.version }}')
          \tProjectSettings.save()
          " > $script

          godot --headless --script $script
          rm $script

      - name: Generate Changelog
        id: generate-changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.4
        with:
          futureRelease: ${{ github.event.inputs.version }}
      - name: Write CHANGELOG.md
        run: |
          printf "${{ steps.generate-changelog.outputs.changelog }}" > CHANGELOG.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Bump version to ${{ github.event.inputs.version }}
          labels: release
          branch: github-actions/bump-version-${{ github.event.inputs.version }}
          commit-message: Bump version to ${{ github.event.inputs.version }}
          body: |
            Bumped project version to ${{ github.event.inputs.version }} and updated CHANGELOG.md.
